version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    container_name: monogo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db

  neo4j: 
    image: neo4j:3.5.17
    container_name: neo4j 
    environment: 
      - NEO4J_AUTH=neo4j/rem8271206
      - NEO4JLABS_PLUGINS=["apoc", "n10s"]
    ports: 
      - 7474:7474
      - 7687:7687
    volumes: 
      - ./data/neo4j/data:/var/lib/neo4j/data
      - ./logs/neo4j/log:/var/lib/neo4j/logs
      - ./addons/neo4j/plugins:/var/lib/neo4j/plugins